<asset:stylesheet src="bootstrap.min.css" />
<asset:stylesheet src="bootstrap-theme.min.css" />
<asset:stylesheet src="datepicker.css" />
<asset:stylesheet src="thmrz.css" />
<asset:javascript src="jquery.min" />
<asset:javascript src="bootstrap.min" />
<asset:javascript src="bootstrap-datepicker" />
<asset:javascript src="thmrz" />
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">